### ISSUE TITLE
Create, print, and share dataviz mockups

### ISSUE THREAD

**Issue by s2t2** [kuanb/atl_zoink#5]
... so we can get feedback on design before implementing/coding.

**Comment by s2t2** [comment]
disclaimer: these charts depict information based on incomplete data and therefore should not be construed as fact.

## Top Violations

![top-violations](https://cloud.githubusercontent.com/assets/1328807/12604356/b695ca8c-c46f-11e5-943e-334f90e6c8b1.png)

## Distribution of Citations per Person

all:

![dist-citations-per-person](https://cloud.githubusercontent.com/assets/1328807/12604523/276846d0-c471-11e5-96f4-323382578b9b.png)

zoomed-in at the lower end:

![dist-citations-per-person-filtered](https://cloud.githubusercontent.com/assets/1328807/12604529/351c8dae-c471-11e5-9456-1312df734f32.png)

**Comment by s2t2** [comment]
printed and shared today

**Comment by s2t2** [comment]
@bpdesigns comment away!

**Comment by bpdesigns** [comment]
I'd love to see a chart of top violations for people who have (1a) up to five citations and another for people who only have (1b) one violation. Two other charts discussed is what the overall data looks like (2) without traffic violations and (3) violations by date. Thanks!

**Comment by s2t2** [comment]
thanks. fyi here is a web version of the generic top violations chart. outstanding: add thousands separators and a helpful subtitle ...

![screenshot 2016-01-29 14 09 53](https://cloud.githubusercontent.com/assets/1328807/12689486/0ee64ad0-c692-11e5-9593-32a3f6ad60d1.png)

**Comment by s2t2** [comment]
FYI @bpdesigns a follow up on your comments:

if you'd like to see charts of violations by category before wednesday, #9 is an opportunity to help categorize them.

and right now i'm not sure about the value of producing charts by person (and with selectors/differentiators for number of violations per person) because we don't have person identifiers. that being said, for demos on wednesday, if i get a chance, i might produce charts by "defendant full name".
